### ISSUE TITLE
The interpolation result heatmap has abnormal deformation on the x-axis

### ISSUE THREAD

**Issue by StarWish365** [Rylern/InterpolateHeatmapLayer#11]
Hello, I encountered some problems when using your open source interpolation API, as shown in the figure below:

In theory, the interpolation result should present circular hot spots around the data points, but in my drawing results, the hot spots are distributed in elongated ellipses along the x-axis. My drawing is based on the Mapbox API, so I want to confirm whether this problem may be related to the coordinate system I use?

I have carefully checked the parameter settings of the interpolation calculation and found no obvious problems. Have you encountered similar situations? Or do you have a recommended solution?

Thank you very much for your help!
![image](https://github.com/user-attachments/assets/75b9cda8-e09f-4940-8bf1-f3b5cace767e)

**Comment by Rylern** [comment]
> I want to confirm whether this problem may be related to the coordinate system I use?

Do you use the [Mercator](https://docs.mapbox.com/mapbox-gl-js/guides/projections/#what-projections-are-available) projection? Only this projection is supported

**Comment by StarWish365** [comment]
> > I want to confirm whether this problem may be related to the coordinate system I use?
> 
> Do you use the [Mercator](https://docs.mapbox.com/mapbox-gl-js/guides/projections/#what-projections-are-available) projection? Only this projection is supported

Yes! Mercator projection is the default projection and I didn't change it. The problem still exists.
![image](https://github.com/user-attachments/assets/c56592e2-5199-45c0-b2f1-fda55ceb8286)
![image](https://github.com/user-attachments/assets/5c048974-153a-4c08-96d0-82da20cf0bd5)

**Comment by Rylern** [comment]
So I think this is related to the nature of the [IDW formula](https://wikimedia.org/api/rest_v1/media/math/render/svg/9c43e9b1f84cc8b358947e4582eb210886c98b4d). If the range of latitude of your points is bigger than the range of longitude of your points, then you see these elongated ellipses along the x-axis.

For example, here is what it looks with 5 points that have the same latitude:
![image](https://github.com/user-attachments/assets/0034564b-c4cb-45db-9b1d-8719a3f065f0)
The ellipses are elongated along the y-axis.

And here is what it looks with 5 points that have the same longitude:
![image](https://github.com/user-attachments/assets/fd7d3eff-f39d-4d4c-9e16-953f1ec23723)
The ellipses are elongated along the x-axis.

I'm not sure if this is the correct explanation though. Does it make sense to you?

**Comment by StarWish365** [comment]
Yeah I think it makes sense. Because I tried setting my map size to a 1:1 aspect ratio and the heatmap stretching stopped happening. Thanks a lot.

**Comment by StarWish365** [comment]
Hello, I found that whether my heat map is stretched or not is related to the map size I set. When my map‘s width is larger than height, the heat map is stretched on the x-axis, and when the height is larger than the width, it is stretched on the y-axis. 
![image](https://github.com/user-attachments/assets/4ac8738b-ccce-4762-9f13-63d28c1501f4)
![image](https://github.com/user-attachments/assets/7bf2a2f7-c0f1-4c90-bfd2-f2477ed06116)

My current solution is to set the map width and height to 1:1. Do you have any solution so that I can get a normal heat map on a non-square map?

**Comment by Rylern** [comment]
You're right. I spent a few days thinking of a solution and I came up with a very simple one. Could you try version 1.6.1 and tell me if it's good for you?

**Comment by StarWish365** [comment]
> You're right. I spent a few days thinking of a solution and I came up with a very simple one. Could you try version 1.6.1 and tell me if it's good for you?

Hi, I tried the new version and it works perfectly now. Thanks!
