### ISSUE TITLE
Generate Heatmap from a regular grid of points

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [Rylern/InterpolateHeatmapLayer#3]
## Feature Request or Question

Hello,

I tried to use the InterpolateHeatmapLayer to create a Seafloor depth heatmap.

As `points` input, I have 257 measures of seafloor depth, spread over a regular grid as follows:

![image](https://user-images.githubusercontent.com/26741864/149354454-65237a5d-3289-49b9-a68c-9f516197bfe8.png)

The created Heatmap layer with the default parameters looks like:

![image](https://user-images.githubusercontent.com/26741864/149355142-4765aa20-b0ce-4b83-a9ff-011ef79e1f41.png)

I wanted to smooth the rendering of the heatmap, so I tried to increase the `p` power parameter to see how it affects the interpolation
With `p=6` the heatmap looks like 

![image](https://user-images.githubusercontent.com/26741864/149356949-f6124bb5-76df-45ae-8a1d-de9422ff70d2.png)

Here we see "squares" having the value of the main measure that is in the center of the "cell", and limits between cells becomes sharp and clear.

I just figured that this case might be interesting to share with you and I would be glad to have your feedback or advice

I guess that the behaviour I wanted to have is something similar to when we increase the `'heatmap-radius'` of mapbox heatmaps.

Many thanks, 

Mohamed Hamou

**Comment by Rylern** [comment]
Hi, could you try to decrease the value of `p` instead?
A low value of `p` will increase the smoothing of the interpolation:
![IDW](https://upload.wikimedia.org/wikipedia/commons/7/71/Shepard_interpolation_2.png)
(taken from [Wikipedia](https://en.wikipedia.org/wiki/Inverse_distance_weighting))
