### ISSUE TITLE
Module bundling issues, `mapboxgl` global dependency

### ISSUE THREAD

**Issue by nfour** [Rylern/InterpolateHeatmapLayer#7]
I'm currently migrating from `https://github.com/vinayakkulkarni/mapbox-gl-interpolate-heatmap/` as I suspect this is a better as you support mapbox-gl v3.

# `mapboxgl` global is implicitly required

One thing I noticed in my migration is that `mapboxgl` global is implicitly required.

Had to do this in my `vite` project:
```ts

import mapboxgl from 'mapbox-gl`
window.mapboxgl = mapboxgl
```

If you can declare `mapbox-gl` as a peer dependency and import it, then let webpack handle the rest, while also marking it as an `external`, this package should be a compatible with modern bundlers.

# Types

I also whipped up a type definition:

```ts
declare module 'interpolateheatmaplayer' {
  import type { CustomLayerInterface } from 'mapbox-gl';

  interface HeatmapPoint {
    lat: number;
    lon: number;
    val: number;
  }

  interface ROI {
    lat: number;
    lon: number;
  }

  interface InterpolateHeatmapLayerOptions {
    points?: HeatmapPoint[];
    layerId?: string;
    opacity?: number;
    minValue?: number;
    maxValue?: number;
    framebufferFactor?: number;
    p?: number;
    roi?: ROI[];
    valueToColor?: string;
    valueToColor4?: string;
    pointRadius?: number;
    fasterPointRadius?: boolean;
    averageThreshold?: number;
  }

  interface InterpolateHeatmapLayer extends CustomLayerInterface {
    updatePoints(points: HeatmapPoint[]): void;
  }

  export function create(
    options: InterpolateHeatmapLayerOptions,
  ): InterpolateHeatmapLayer;
}
```

Might be useful to bundle that, too as `index.d.ts` and in package json `"types": "./index.d.ts"`

To describe my usage, I essentially encapsulated it in this file, using the above d.ts, to make a `vite` and `typescript` friendly version:
```ts
import './interpolateheatmap.d.ts';
import { create as InterpolateHeatmapLayer } from 'interpolateheatmaplayer';
import mapboxgl from 'mapbox-gl';

window.mapboxgl = mapboxgl;

export type InterpolateHeatmapLayerOptions = Parameters<
  typeof InterpolateHeatmapLayer
>[0];

export { InterpolateHeatmapLayer };
```

Then eventually stuffing it into a native mapbox layer under `react-map-gl`

**Comment by Rylern** [comment]
Thanks, I created a [pull request](https://github.com/Rylern/InterpolateHeatmapLayer/pull/8) with the changes you proposed (I removed dependencies on Mapbox and added the type declaration).

Could you check if everything works on your side? I tested it on a TypeScript Vite project but I'm not very familiar with bundling. You can do that by cloning the repo, checking out the `bundling` branch, `npm pack`, and then (in your own project) `npm install path/to/InterpolateHeatmapLayer/interpolateheatmaplayer-1.5.0.tgz` (btw let me know if you know a faster way to test the library).

**Comment by Rylern** [comment]
Taking that as a yes, open a new issue if something doesn't work as expected ;)

**Comment by nfour** [comment]
Sorry I didn't notice you integrated this! Thanks a lot, and great project :)

**Comment by Rylern** [comment]
Thanks
